### ISSUE TITLE
File with .cram extension is actually a .bam

### ISSUE THREAD

**Issue by cmdcolin** [genome-in-a-bottle/giab_latest_release#12]
In this folder ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/Ultralong_OxfordNanopore/combined_2018-08-10/

The file 

ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/Ultralong_OxfordNanopore/combined_2018-08-10/HG002_ONTrel2_16x_RG_HP10xtrioRTG.cram

is apparently actually a BAM it seems and 

ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/Ultralong_OxfordNanopore/combined_2018-08-10/HG002_ONTrel2_16x_RG_HP10xtrioRTG.cram.crai

is a BAI

**Comment by cmdcolin** [comment]
Another note:

ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/Ultralong_OxfordNanopore/combined_2018-08-10/HG002_ONTrel2_16x_RG_HP10xtrioRTG.cram

refers to hs37d5 in the header, however, as it is a BAM, I tried adding samtools calmd to it, but it behaved badly with many mismatches

There is the ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/Ultralong_OxfordNanopore/combined_2018-08-10/combined_2018-08-10.hg38.sorted.cram which refers to GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna


Running the calmd on this file results in many NM recalculations which seems like it could indicate the wrong reference?

samtools calmd -@2 -b HG002_ONTrel2_16x_RG_HP10xtrioRTG.bam  hs37d5.fa > HG002_ONTrel2_16x_RG_HP10xtrioRTG.calmd.bam



Edit: I posted that the hg38 fixed it but I was just impatient, it actually also has NM recalculations

**Comment by cmdcolin** [comment]
Edit: posted that hg38 worked better with calmd but it didn't actually. Still has many NM recalculations in both hs37d5 and GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna (with chr1 renamed to 1, etc.)

**Comment by cmdcolin** [comment]
One of the things that surprised me was that this BAM (e.g. the one mislabled as CRAM) contains no sequence, probably explains the above calmd issues

**Comment by nate-d-olson** [comment]
Thank you Colin, for letting us know about the file issues. The combined_2018_08_10 files are from an intermediate release. We are making a new release, which you will be available at `ftp://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/HG002_NA24385_son/Ultralong_OxfordNanopore/guppy-V3.2.4_2020-01-22` in the next few days.  Let us know if you need to use the `combined_2018_08_10` release and I will look into the issue further.

**Comment by cmdcolin** [comment]
nope this is great, I was just looking for test data on phased alignments, thanks!
