### ISSUE TITLE
Chinese son FTP links are broken 

### ISSUE THREAD

**Issue by brendanofallon** [genome-in-a-bottle/giab_latest_release#4]
This is probably an issue with the FTP site and not the code here... but all the links for the latest version of the chinese son data are broken :( 

 For instance: https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/ChineseTrio/HG005_NA24631_son/GRCh38/  leads to a 404 / object not found. Other links have similar errors

**Comment by chunlinxiao** [comment]
just tried - not seeing any problem:

ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/ChineseTrio/HG005_NA24631_son/latest/GRCh38/

try to use  ftp:// instead of https://

**Comment by brendanofallon** [comment]
Hmm, that link you tried works correctly, but it's not the one on the ftp page that is linked to from the readme. To clarify, the link on the readme correctly goes to https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/ChineseTrio/HG005_NA24631_son/latest), but all the links there are broken. 
 The issue seems to be that the links on that page do not include the "latest" entry, they look like this:
 https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/ChineseTrio/HG005_NA24631_son/GRCh38/
Instead, the links should look like this:
 https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/ChineseTrio/HG005_NA24631_son/latest/GRCh38/

**Comment by jzook** [comment]
I think this is now fixed, but let us know if there are still problematic readme's - thanks for reporting it!
