### ISSUE TITLE
Is haplotype information in the GT field of neighboring variants consistent?

### ISSUE THREAD

**Issue by anands-repo** [genome-in-a-bottle/giab_latest_release#8]
Hello,

In the NA12878 VCF, in the high-confidence region, lets say two variant records are nearby (say at a distance of 100 bases from each other) and the first has the GT field 0/1, and the other has the GT field 1/0, then does it mean that the two haplotypes in the region are (REF, 99 ref bases, ALT) and (ALT, 99 bases, REF)? Or are other combinations possible (e.g., (REF, 99 ref bases, REF) and (ALT, 99 bases, ALT))?

Thank you!

**Comment by jzook** [comment]
I apologize for not seeing this before.  In general, if the GT field has a '/', the variants are not phased haplotypes.  However, if the GT field has a '|', then the variants can be assumed to be phased, so that if one variant is 0|1 and the other nearby is 1|0 then they are on opposite haplotypes.
